backend:
  name: git-gateway
  branch: master

media_folder: static/images/upload
public_folder: /images/upload

locale: 'nl'

collections:
  - name: 'general'
    label: 'General configuration'
    format: 'json'
    folder: 'assets/content/general'
    create: true
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: social
    fields:
      - name: 'social'
        label: 'Social Media Links'
        widget: list
        allow_add: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Link Address', name: 'link', widget: 'string' }
          - {
              label: 'FontAwesome icon class',
              name: 'FAIconClass',
              widget: 'string',
            }

  - name: 'persons'
    label: 'Vrouwen in de serie'
    label_singular: 'Vrouw'
    description: >
      Voeg hieronder vrouwen toe aan de serie of verwijder deze.
    format: 'json'
    folder: 'assets/content/women'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{first_name}}-{{last_name}}-{{slug}}'
    summary: '{{first_name}} {{last_name}}'
    editor:
      preview: false
    identifier_field: last_name
    fields:
      - { label: 'positie in de fotoserie', name: 'position', widget: 'number' }
      - { label: 'Voornaam', name: 'first_name', widget: 'string' }
      - { label: 'Achternaam', name: 'last_name', widget: 'string' }
      - label: 'Beroep'
        name: 'profession'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Functie'
        name: 'function'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Uitspraken'
        name: 'quotes'
        widget: 'list'
        allow_add: true
        field:
          - label: 'Quote'
            name: 'quote'
            widget: object
            fields:
              - { label: 'NL', name: 'nl', widget: 'string', required: true }
              - { label: 'EN', name: 'en', widget: 'string', required: false }
      - { label: 'Uitgelichte foto', name: 'image', widget: 'image' }
