backend:
  name: git-gateway
  branch: master

media_folder: static/images/upload
public_folder: /images/upload

locale: 'nl'

collections:
  - name: 'general'
    label: 'General configuration'
    format: 'json'
    folder: 'assets/content/general'
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: social
    fields:
      - name: 'social'
        label: 'Social Media Links'
        widget: list
        allow_add: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Link Address', name: 'link', widget: 'string' }
          - {
              label: 'FontAwesome icon class',
              name: 'FAIconClass',
              widget: 'string',
            }
  - name: 'information'
    label: 'Informatie'
    description: >
      Pas hier de tekst van de pagina 'informatie' aan.
    format: 'json'
    folder: 'assets/content'
    create: true
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: pagename
    fields:
      - { label: 'Naam van de pagina', name: 'pagename' widget: 'text' }
      - label: 'Tekst'
        name: 'text'
        widget: 'object'
        fields:
          - { name: 'introduction', label: 'Introductie', widget: 'text' }
          - { name: 'quote', label: 'Quote', widget: 'text' }
          - { name: 'author', label: 'Auteur', widget: 'string' }
      - label: 'Dankwoord'
        name: 'thanks'
        widget: 'object'
        fields:
          - label: 'koptekst'
            name: 'head'
            widget: 'string'
          - label: 'medewerker'
            name: 'helper'
            widget: 'list'
            allow_add: true
            fields:
              - {
                  label: 'Taak',
                  name: 'task',
                  widget: 'string',
                  required: true,
                }
              - {
                  label: 'Naam',
                  name: 'name',
                  widget: 'string',
                  required: true,
                }

  - name: 'persons'
    label: 'Vrouwen in de serie'
    label_singular: 'Vrouw'
    description: >
      Pas hieronder de informatie over de vrouwen in de serie aan.
    format: 'json'
    folder: 'assets/content/women'
    create: true
    slug: '{{position}}-{{first_name}}-{{last_name}}'
    summary: '{{first_name}} {{last_name}} ({{position}})'
    editor:
      preview: false
    identifier_field: last_name
    fields:
      - { label: 'positie in de fotoserie', name: 'position', widget: 'number' }
      - { label: 'Voornaam', name: 'first_name', widget: 'string' }
      - { label: 'Achternaam', name: 'last_name', widget: 'string' }
      - label: 'Beroep'
        name: 'profession'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Functie'
        name: 'function'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Uitspraken'
        name: 'quotes'
        widget: 'list'
        allow_add: true
        fields:
          - label: 'Quote'
            name: 'quote'
            widget: object
            fields:
              - { label: 'NL', name: 'nl', widget: 'string', required: true }
              - { label: 'EN', name: 'en', widget: 'string', required: false }
      - { label: 'Uitgelichte foto', name: 'image', widget: 'image' }
