backend:
  name: git-gateway
  branch: master

media_folder: static/images/upload
public_folder: /images/upload

locale: 'nl'

collections:
  - name: 'general'
    label: 'General configuration'
    format: 'json'
    folder: 'assets/content/general'
    create: true
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: social
    fields:
      - name: 'social'
        label: 'Social Media Links'
        widget: list
        allow_add: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Link Address', name: 'link', widget: 'string' }
          - {
              label: 'FontAwesome icon class',
              name: 'FAIconClass',
              widget: 'string',
            }

  - name: 'persons'
    label: 'Persons in the series'
    label_singular: 'Person'
    description: >
      The persons in the list below will be shown on the website.
    format: 'json'
    folder: 'assets/content/women'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{first_name}}-{{last_name}}-{{slug}}'
    summary: '{{first_name}} {{last_name}}'
    editor:
      preview: true
    identifier_field: last_name
    fields:
      - { label: 'positie in de fotoserie', name: 'position', widget: 'number' }
      - { label: 'Voornaam', name: 'first_name', widget: 'string' }
      - { label: 'Achternaam', name: 'last_name', widget: 'string' }
      - { label: 'Beroep', name: 'profession', widget: 'string' }
      - {
          label: 'Beroep (EN)',
          name: 'profession_en',
          widget: 'string',
          required: false,
        }
      - { label: 'Functie', name: 'function', widget: 'string' }
      - {
          label: 'Functie (EN)',
          name: 'function_en',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Uitspraken',
          name: 'quotes',
          widget: 'list',
          allow_add: true,
          field: { label: 'Quote', name: 'quote', widget: string },
        }
      - {
          label: 'Uitspraken (EN)',
          name: 'quotes_en',
          widget: 'list',
          allow_add: true,
          field: { label: 'Quote', name: 'quote_en', widget: string },
          required: false,
        }
      - { label: 'Uitgelichte foto', name: 'image', widget: 'image' }
