backend:
  name: git-gateway
  branch: master

media_folder: static/images/upload
public_folder: /images/upload

locale: 'nl'
logo_url: https://www.onbevangen-hetproject.nl/images/logo-cms.png
display_url: https://www.onbevangen-hetproject.nl/

collections:
  - name: 'general'
    label: 'Algemene instellingen'
    description: >
      Pas hier de algemene instellingen van de website aan, zoals bijvoorbeeld de social media links.
    format: 'json'
    folder: 'assets/content/general'
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: componentname
    fields:
      - {
          label: 'Naam van de component',
          name: 'componentname',
          widget: 'string',
        }
      - name: 'social'
        label: 'Social Media Links'
        widget: list
        allow_add: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Link Address', name: 'link', widget: 'string' }
          - {
              label: 'FontAwesome icon class',
              name: 'FAIconClass',
              widget: 'string',
            }

  - name: 'nieuws'
    label: 'Nieuws'
    description: >
      Pas hier de tekst van de pagina 'Nieuws' aan.
    format: 'json'
    folder: 'assets/content/news'
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: pagename
    fields:
      - { label: 'Naam van de pagina', name: 'pagename', widget: 'string' }
      - { label: 'Koptekst', name: 'head', widget: 'text' }
      - label: 'alineas'
        label_singular: 'Alinea'
        name: 'alineas'
        widget: 'list'
        allow_add: true
        fields:
          - { label: 'Tekst', name: 'text', widget: 'text', required: true }

  - name: 'information'
    label: 'Informatie'
    description: >
      Pas hier de tekst van de pagina 'Informatie' aan.
    format: 'json'
    folder: 'assets/content/information'
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    identifier_field: pagename
    fields:
      - { label: 'Naam van de pagina', name: 'pagename', widget: 'string' }
      - label: 'Tekst'
        name: 'text'
        widget: 'object'
        fields:
          - { name: 'introduction', label: 'Introductie', widget: 'text' }
          - { name: 'quote', label: 'Quote', widget: 'text' }
          - { name: 'author', label: 'Auteur', widget: 'string' }
      - label: 'Dankwoord'
        name: 'thanks'
        widget: 'object'
        fields:
          - label: 'koptekst'
            name: 'head'
            widget: 'string'
          - label: 'medewerker'
            name: 'helpers'
            widget: 'list'
            allow_add: true
            fields:
              - {
                  label: 'Taak',
                  name: 'task',
                  widget: 'string',
                  required: true,
                }
              - {
                  label: 'Naam',
                  name: 'name',
                  widget: 'string',
                  required: true,
                }

  - name: 'persons'
    label: 'Vrouwen in de serie'
    label_singular: 'Vrouw'
    description: >
      Pas hieronder de informatie over de vrouwen in de serie aan.
    format: 'json'
    folder: 'assets/content/women'
    create: true
    slug: '{{position}}-{{first_name}}-{{last_name}}'
    summary: '{{first_name}} {{last_name}} ({{position}})'
    editor:
      preview: false
    identifier_field: last_name
    fields:
      - { label: 'positie in de fotoserie', name: 'position', widget: 'number' }
      - { label: 'Voornaam', name: 'first_name', widget: 'string' }
      - { label: 'Achternaam', name: 'last_name', widget: 'string' }
      - label: 'Beroep'
        name: 'profession'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Functie'
        name: 'function'
        widget: 'object'
        fields:
          - { label: 'NL', name: 'nl', widget: 'string', required: true }
          - { label: 'EN', name: 'en', widget: 'string', required: false }
      - label: 'Uitspraken'
        name: 'quotes'
        widget: 'list'
        allow_add: true
        fields:
          - label: 'Quote'
            name: 'quote'
            widget: object
            fields:
              - { label: 'NL', name: 'nl', widget: 'string', required: true }
              - { label: 'EN', name: 'en', widget: 'string', required: false }
      - { label: 'Uitgelichte foto', name: 'image', widget: 'image' }

  - name: 'newsitems'
    label: 'Nieuwsberichten'
    label_singular: 'Nieuwsbericht'
    description: >
      Voeg hieronder nieuwsberichten aan de website toe.
    format: 'json'
    folder: 'assets/content/newsitems'
    create: true
    slug: '{{title}}-{{date}}'
    summary: '{{title}}-{{date}}'
    editor:
      preview: false
    identifier_field: date
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Publicatie-datum', name: 'date', widget: 'datetime' }
      - { label: 'Beschrijving', name: 'description', widget: 'string' }
      - { label: 'Tekst', name: 'body', widget: 'markdown' }
